[package]
name = "tui-markup"
version = "0.2.0"
authors = ["7sDream <i@7sdre.am>"]
edition = "2021"
description = "markup langauge for terminal styled text"
documentation = "https://docs.rs/tui-markup"
readme = "README.md"
homepage = "https://github.com/7sDream/tui-markup"
repository = "https://github.com/7sDream/tui-markup"
license = "BSD-3-Clause-Clear"
keywords = ["terminal", "tui", "markup", "text", "parser"]
categories = ["command-line-interface", "parser-implementations", "text-processing"]
exclude = ["examples/*.png"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
ansi = ["ansi_term"]

[dependencies]
nom = "7"
nom_locate = { version = "4", features = ["runtime-dispatch-simd"] }
thiserror = "1"
# generator implementations
ansi_term = { version = "0.12", optional = true }
tui = { version = "0.19", optional = true, default-features = false }

[dev-dependencies]
tui = "0.19"
crossterm = "0.25"
ansi_term = "0.12"

[[example]]
name = "tui"
required-features = ["tui"]

[[example]]
name = "ansi"
required-features = ["ansi"]

[[example]]
name = "common"
crate-type = ["rlib"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
