[env]
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--all-targets --all-features"

[tasks.copy-apidocs]
disabled = true

[tasks.docs]
args = ["doc", "--no-deps", "--all-features"]

[tasks.opendocs]
description = "Generate rust documentation and open it."
categories = "Documentation"
install_crate = false
command = "cargo"
args = ["doc", "--all-features", "--open"]

[tasks.opendocsrs]
description = "Preview generated document when publish to docs.rs"
categories = "Documentation"
install_crate = false
env = { RUSTDOCFLAGS = "--cfg docsrs" }
command = "cargo"
args = ["+nightly", "doc", "--no-deps", "--all-features", "--open"]
