[env]
# add --all-targets for run test in examples
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--all-targets --all-features"

# ===== default flow tasks override =====

[tasks.copy-apidocs]
# do not need api docs into git repo
disabled = true

[tasks.docs]
# add --all-features
args = ["doc", "--no-deps", "--all-features"]

# ==== custom tasks =====

[tasks.opendocs]
description = "Generate rust documentation and open it."
category = "Documentation"
install_crate = false
command = "cargo"
args = ["doc", "--all-features", "--open"]

[tasks.opendocsrs]
description = "Preview generated document when publish to docs.rs"
category = "Documentation"
install_crate = false
env = { RUSTDOCFLAGS = "--cfg docsrs" }
command = "cargo"
args = ["+nightly", "doc", "--no-deps", "--all-features", "--open"]
