edition = "2021"
fn_args_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 120
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
spaces_around_ranges = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
