items = { item };

item
= text
| element
;

text = char, { char };

char
= normal char
| escaped char
;

normal char = ? any unicode character ? - '\' - '<' - '>';

escaped char
= "\\"
| "\<"
| "\>"
;

element = '<', tags, ' ', items, '>';

tags = tag, { ',', tag };

tag
= [ [ "fg" | "bg" ], ':' ], color
| [ "mod", ':' ], midifier
| custom-tag
;

tag char =
| (? alphanumberic character ?)
| '+' | '-' | ':'
;

color = { tag char - ':' };

midifier = { tag char - ':' };

(* Please read generator's document for real color and modifier they supports *)

custom-tag = { tag char };
