tag
= [ [ "fg" | "bg" ], ':' ], color
| [ [ "mod" ], ':' ], modifier
;

color
= "black"
| "white"
| light variant colors, [ '-' ]
| dark variant colors, [ '+' ]
| custom color
;

light variant colors
= "red"
| "green"
| "yellow"
| "blue"
| "magenta"
| "cyan"
;

dark variant colors = "gray";

custom color = 6 * hex digit;

hex digit
= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
| 'a' | 'b' | 'c' | 'd' | 'e' | 'f'
| 'A' | 'B' | 'C' | 'D' | 'E' | 'F'
;

(* bold *)
(* dim *)
(* italic *)
(* underline *)
(* slow blink *)
(* rapid blink *)
(* hide *)
(* cross/delete line *)
modifier
= 'b' 
| 'd' 
| 'i' 
| 'u' 
| 's' 
| 'r' 
| 'h' 
| 'x' 
;
